name: Check

on:
    push:
        branches:
            - '*'

        # We tag this repo with a tag for every project when we want to
        # release. But we really don't need to spend the time checking against
        # all of those tags when we've already checked the commit.
        tags:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Environment variables
              run: echo -e "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME\nGITHUB_EVENT_PATH=$GITHUB_EVENT_PATH\nGITHUB_REF=$GITHUB_REF"

            - name: cat events
              run: cat $GITHUB_EVENT_PATH

            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Output git log
              run: git log --pretty=format:"* %s"

#            - name: Make git log an output?
#              id: generate-log
#              run: |
#                  output=$(git log --pretty=format:"* %s")
#                  echo "::set-output name=log::$output"
#
#            - name: Test output
#              run: echo ${{ steps.generate-log.outputs.log }}

            - name: Test a multi-line output with newlines?
              id: multi-line
              run: |
                  echo "::set-output name=log::one\\"
                  echo "two\\"
                  echo "three"

            - name: Test output
              run: echo '"${{ steps.multi-line.outputs.log }}"'
